Step 3: Fetched array list
gracetian6/step pull request #7
Opened 2020-06-02 21:18 UTC by gracetian6

Step 3 was about JSON. The task is to modify DataServlet.java to return some hard-coded JSON data, and then modify script.js to fetch that JSON and build a UI from it.

2020-06-02 22:44 UTC, jessicaslaughter approved these changes

2020-06-02 22:44 UTC, jessicaslaughter commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    System.out.println(msgs);
now that you confirmed this works, you can remove the system.out.println statements

2020-06-03 00:56 UTC, jpnickolas requested changes

2020-06-03 00:56 UTC, geekster777 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    System.out.println(msgs);
Remove debug statements

2020-06-03 00:56 UTC, geekster777 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    String json = convertToJson(msgs);
use `gson.toJson(msgs);` instead of writing your own helper.

2020-06-03 16:38 UTC, jpnickolas approved these changes
Looks good Grace!

2020-06-03 16:44 UTC, merged